services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${GOBID_APP_PORT}:${GOBID_APP_PORT}
    environment:
      - GOBID_DATABASE_HOST=db
      - GOBID_APP_PORT=${GOBID_APP_PORT}
      - GOBID_DATABASE_PORT=${GOBID_DATABASE_PORT}
      - GOBID_DATABASE_NAME=${GOBID_DATABASE_NAME}
      - GOBID_DATABASE_USER=${GOBID_DATABASE_USER}
      - GOBID_DATABASE_PASSWORD=${GOBID_DATABASE_PASSWORD}
      - GOBID_CSRF_KEY=${GOBID_CSRF_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${GOBID_DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${GOBID_DATABASE_USER}
      - POSTGRES_PASSWORD=${GOBID_DATABASE_PASSWORD}
      - POSTGRES_DB=${GOBID_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GOBID_DATABASE_USER} -d ${GOBID_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db:
    driver: local