FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o ./bin/main ./cmd/api

FROM scratch

WORKDIR /app

COPY --from=builder /app/bin/main .

EXPOSE 3000

ENTRYPOINT [ "/app/main" ]